import moonimage from '../images/moon.jpg';
import callistoimage from '../images/Callisto.jpg';
import ioimage from '../images/io.jpg';
import charonimage from '../images/charon.jpg';
import enceladusimage from '../images/enceladus.jpg';
import europaimage from '../images/europa.jpg';
import ganymedeimage from '../images/ganymede.jpg';
import phobosimage from '../images/phobos.jpg';
import titanimage from '../images/titan.jpg';
import tritonimage from '../images/triton.jpg';

const Data = [
    {name:'The Moon',
     planet:'Earth',
     info: 'At only 385 000 km from Earth, this makes The Moon our most accessible celestial body for you to call home. Enjoy superb views of the Earth from your patio!',
     image: moonimage,
     price: 30000000,
     count: 0,
    },
    {name:'Phobos',
    planet:'Mars',
    info:'One of your smallest moon for you to acquire land ownership on makes it our most intimate moon. Home of a one of a kind 10 km wide crater!',
    image: phobosimage,
    price: 40000000,
    count: 0,
   },
    {name:'Callisto',
     planet:'Jupiter',
     info: "Fans of ice will enjoy the icy surface of Callisto and explorers of ocean depths can wander underneath the ice in Callisto's underground ocean. You might even find some surprising life forms down there!",
     image: callistoimage,
     price: 50000000,
     count: 0,
    },
    {name:'Io',
     planet:'Jupiter',
     info: "You like it warm? You like action? Look no further, Io has hundreds of active volcalnoes to keep you on your toes. No more snowy winters for you!",
     image: ioimage,
     price: 70000000,
     count: 0,
    },
    {name:'Ganymede',
     planet: 'Jupiter',
     info: 'Welcome on the largest moon we have to offer! Outdoorsy peeps will love the wide open space of Ganymede. You can even travel around on its surface in your ice skates!',
     image: ganymedeimage,
     price: 50000000,
     count: 0,
   },
   {name:'Europa',
     planet: 'Jupiter',
     info: 'You like it on Earth? Well Europa might be just for you. It has salty liquid water, ice, a rocky mantle and might even harbour some life! Come check it out for yourself!',
     image: europaimage,
     price: 50000000,
     count: 0,
    },
   {name:'Enceladus',
     planet: 'Saturn',
     info: 'Not into craters and potholes? Come live on Enceladus and enjoy a smooooth clean white surface. Do not forget your coat though, it can get quite cold at times (down to minus 201 degrees Celcius).',
     image: enceladusimage,
     price: 40000000,
     count: 0,
    },
    {name:'Titan',
    planet:'Saturn',
    info:"Breathing profundly while kayaking on wild rivers, sounds like something you would miss on Earth? No, you will not if you get some land on Saturn's largest moon!",
    image: titanimage,
    price: 60000000,
    count: 0,
   },
    {name:'Triton',
     planet:'Neptune',
     info:"You like to live on your terms and go your own way even if everybody is going the other direction? We have the moon just for you. Triton is the only moon orbiting in the opposite direction as its planet rotation. Talk about strong independency!",
     image: tritonimage,
     price: 40000000,
     count: 0,
    },
    {name:'Charon',
     planet:'Pluto',
     info: 'Real adventure awaits those who are willing to travel to our furthest moon. Only about 20 000 km from Pluto, buying land on Charon also means enjoying easy access to another planet!',
     image: charonimage,
     price: 90000000,
     count: 0,
    },
];

export default Data