import moonimage from '../images/moon.jpg';
import callistoimage from '../images/Callisto.jpg';
import ioimage from '../images/io.jpg';
import charonimage from '../images/charon.jpg';
import enceladusimage from '../images/enceladus.jpg';
import europaimage from '../images/europa.jpg';
import ganymedeimage from '../images/ganymede.jpg';
import phobosimage from '../images/phobos.jpg';
import titanimage from '../images/titan.jpg';
import tritonimage from '../images/triton.jpg';

const Data = [
    {name:'The Moon',
     planet:'Earth',
     info: 'To be added',
     image: moonimage,
     price: 30000000,
     count: 0,
    },
    {name:'Phobos',
    planet:'Mars',
    info:'To be added',
    image: phobosimage,
    price: 40000000,
    count: 0,
   },
    {name:'Callisto',
     planet:'Jupiter',
     info: 'To be added',
     image: callistoimage,
     price: 50000000,
     count: 0,
    },
    {name:'Io',
     planet:'Jupiter',
     info: 'To be added',
     image: ioimage,
     price: 70000000,
     count: 0,
    },
    {name:'Ganymede',
     planet: 'Jupiter',
     info: 'To be added',
     image: ganymedeimage,
     price: 50000000,
     count: 0,
   },
   {name:'Europa',
     planet: 'Jupiter',
     info: 'To be added',
     image: europaimage,
     price: 50000000,
     count: 0,
    },
   {name:'Enceladus',
     planet: 'Saturn',
     info: 'To be added',
     image: enceladusimage,
     price: 40000000,
     count: 0,
    },
    {name:'Titan',
    planet:'Saturn',
    info:'To be added',
    image: titanimage,
    price: 60000000,
    count: 0,
   },
    {name:'Triton',
     planet:'Neptune',
     info:'To be added',
     image: tritonimage,
     price: 40000000,
     count: 0,
    },
    {name:'Charon',
     planet:'Pluto',
     info: 'To be added',
     image: charonimage,
     price: 90000000,
     count: 0,
    },
];

export default Data